#ifndef _TMR_CONFIG_H_
#define _TMR_CONFIG_H_
/* PRESCALER MODES
TMR_PRESCALER_1
TMR_PRESCALER_89
TMR_PRESCALER_64
TMR_PRESCALER_256
TMR_PRESCALER_1024
*/

#define TMR_MODE  TMR_CTC
#define TMR1_MODE TMR1_NORM


#define TMR_CTC_OUTPUT TMR_CTC_NORM	

#define TMR_PWMF_MODE TMR_PWMF_CLROC

#define TMR_PRESCALER TMR_PRESCALER_8

#define TMR_CMPVALUE 249
#define TMR_PRELOADVALUE 238

#endif